# The URL the site will be built for
base_url = "https://danwilson.co"

# title + description
title = "$ man dwlsn"
description = "Personal website of Dan Wilson the Software Engineer"

# theme
theme = "zola-bearblog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Build RSS feed
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "tags"},
]
default_language = "en"

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"


[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "inline"

# Selecting a theme is always required: you have a choice between single (1) or dual themes (2).
# Only outputting CSS classes like before 0.22 is not possible anymore.
# 1. If you use a single theme, put its name here. See the syntax highlighting page for the possible choices.
theme = "github-dark"


[extra]
# Put all your custom variables here
translations = [
  { code = "en", name = "English" },
]

# date string format
date_format = "%d %b %Y"

# menu is enabled by adding menu_items (optional)
blog_list = "@/posts/_index.md"
main_menu = [
    {name = "about", url = "@/pages/about.md"},
    {name = "cv", url = "@/pages/cv.md"},
    {name = "posts", url = "@/posts/_index.md"},
    {name = "now", url = "@/now/_index.md"},
    {name = "ideas", url = "@/ideas/_index.md"},
    {name = "colophon", url = "@/pages/colophon.md"},
]

# page title
page_titles = "combined"
